#funciones
languaje = "python"
print(languaje.capitalize())
print(languaje.upper())
print(languaje.lower())
print(languaje.count("t"))
print(languaje.find("t"))
print(languaje.isalnum())
print(languaje.isalpha())
print(languaje.isdigit())
print(languaje.islower())
print(languaje.isspace())
print(languaje.istitle())
print(languaje.isupper())
print(languaje.endswith("n"))
print(languaje.startswith("p"))
print(languaje.replace("p", "j"))
print(languaje.replace("p", "j", 1))
print(languaje.split())
print(languaje.split("t"))
print(languaje.split("t", 1))
print(languaje.split("t", 2))
print(languaje.split("t", 3))
print(languaje.split("t", 4))
print(languaje.split("t", 5))
print(languaje.split("t", 6))
print(languaje.split("t", 7))